document.write( '<!-- footer -->\n' );
document.write( '    <footer class=\"footer\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <ul class=\"text-gp\">\n' );
document.write( '                <li>\n' );
document.write( '                    <a href=\"information.html\"><i class=\"fas fa-file-alt\"></i>政府網站資料開放宣告</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li>\n' );
document.write( '                    <a href=\"private.html\"><i class=\"fas fa-file-alt\"></i>隱私權保護政策</a>\n' );
document.write( '                </li>\n' );
document.write( '                <li>\n' );
document.write( '                    <a href=\"security.html\"><i class=\"fas fa-file-alt\"></i>網站安全政策</a>\n' );
document.write( '                </li>\n' );
document.write( '            </ul>\n' );
document.write( '            <div class=\"contact\">\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"fas fa-map-marker-alt\"></i>新市政大樓</h4>\n' );
document.write( '                    <p>407201 臺中市西屯區臺灣大道三段99號惠中樓（A棟）10樓</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"fas fa-map-marker-alt\"></i>陽明大樓</h4>\n' );
document.write( '                    <p>420018 臺中市豐原區陽明街36號2樓</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"fas fa-mobile-alt\"></i>聯絡電話</h4>\n' );
document.write( '                    <p>市話總機代表號：04-22289111，本局傳真號碼：25260450</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"far fa-clock\"></i>辦公時間</h4>\n' );
document.write( '                    <p>8:00-17:00，中午休息時間：12:00-13:00，彈性上下班時間：8:00-8:30、13:00-13:30、17:00-17:30</p>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"notice\">\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <p>建議使用瀏覽器 Firefox58.0以上或IE10.0以上或google chrome版本瀏覽本站</p>\n' );
document.write( '                    <p>臺中市政府運動局版權所有 Copyright © 2018. All Rights Reserved.</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"date\">\n' );
document.write( '                    <p>最後更新：2020/09/09</p>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </footer>\n' );
document.write( '\n' );
document.write( '    <a href=\"#top\">\n' );
document.write( '        <div class=\"back-top\">▲</div>\n' );
document.write( '    </a>\n' );
document.write( '\n' );
document.write( '    <!-- bootstrap -->\n' );
document.write( '    <script src=\"https://code.jquery.com/jquery-3.4.1.slim.min.js\"\n' );
document.write( '        integrity=\"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n\"\n' );
document.write( '        crossorigin=\"anonymous\"></script>\n' );
document.write( '    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\n' );
document.write( '        integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\n' );
document.write( '        crossorigin=\"anonymous\"></script>\n' );
document.write( '    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\n' );
document.write( '        integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\n' );
document.write( '        crossorigin=\"anonymous\"></script>\n' );
document.write( '\n' );
document.write( '    <!-- mobile-menu -->\n' );
document.write( '    <script>\n' );
document.write( '        var fas = document.querySelector(\".fas.fa-bars\")\n' );
document.write( '        var navbar_nav = document.querySelector(\".nav.navbar-nav\")\n' );
document.write( '        var nav_item = document.querySelector(\".nav-item.dropdown\")\n' );
document.write( '        fas.onclick = function () {\n' );
document.write( '            if (navbar_nav.classList.contains(\"active-ul\")) {\n' );
document.write( '                navbar_nav.classList.remove(\"active-ul\")\n' );
document.write( '            } else {\n' );
document.write( '                navbar_nav.classList.add(\"active-ul\")\n' );
document.write( '            }\n' );
document.write( '        }\n' );
document.write( '    </script>\n' );
document.write( '\n' );
document.write( '    <!-- Swiper JS -->\n' );
document.write( '    <script src=\"https://unpkg.com/swiper/swiper-bundle.js\"></script>\n' );
document.write( '    <script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\n' );
document.write( '\n' );
document.write( '    <!-- Initialize Swiper -->\n' );
document.write( '    <script>\n' );
document.write( '        var swiper = new Swiper(\'.swiper-container\', {\n' );
document.write( '            slidesPerView: 1,\n' );
document.write( '            // loop: true,\n' );
document.write( '            pagination: {\n' );
document.write( '                el: \'.swiper-pagination\',\n' );
document.write( '                clickable: true,\n' );
document.write( '            },\n' );
document.write( '            navigation: {\n' );
document.write( '                nextEl: \'.swiper-button-next\',\n' );
document.write( '                prevEl: \'.swiper-button-prev\',\n' );
document.write( '            },\n' );
document.write( '            // autoplay: {\n' );
document.write( '            //     delay: 2500,\n' );
document.write( '            //     disableOnInteraction: false,\n' );
document.write( '            // },\n' );
document.write( '        });\n' );
document.write( '    </script>' );
