document.write( '<!-- footer -->\n' );
document.write( '    <footer class=\"footer\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <a href=\"#Z\" id=\"AZ\" title=\"下方功能區塊\" accesskey=\"Z\"></a>\n' );
document.write( '            <div class=\"text-gp\">\n' );
document.write( '                <button type=\"button\" class=\"btn-outline outline-BK\"\n' );
document.write( '                    onclick=\"javascript:location.href=\'information.html\'\">政府網站資料開放宣告</button>\n' );
document.write( '                <button type=\"button\" class=\"btn-outline outline-BK\"\n' );
document.write( '                    onclick=\"javascript:location.href=\'private.html\'\">隱私權政策</button>\n' );
document.write( '                <button type=\"button\" class=\"btn-outline outline-BK\"\n' );
document.write( '                    onclick=\"javascript:location.href=\'security.html\'\">資訊安全政策</button>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"contact\">\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"fas fa-map-marker-alt\"></i>新市政大樓</h4>\n' );
document.write( '                    <p>407201 臺中市西屯區臺灣大道三段99號惠中樓（A棟）10樓</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"fas fa-map-marker-alt\"></i>陽明大樓</h4>\n' );
document.write( '                    <p>420018 臺中市豐原區陽明街36號2樓</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"fas fa-mobile-alt\"></i>聯絡電話</h4>\n' );
document.write( '                    <p>市話總機代表號：04-22289111，本局傳真號碼：25260450</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <h4><i class=\"far fa-clock\"></i>辦公時間</h4>\n' );
document.write( '                    <p>8:00-17:00，中午休息時間：12:00-13:00，彈性上下班時間：8:00-8:30、13:00-13:30、17:00-17:30</p>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"notice\">\n' );
document.write( '                <div class=\"text-gp\">\n' );
document.write( '                    <p>建議使用瀏覽器 Firefox58.0以上或IE10.0以上或google chrome版本瀏覽本站</p>\n' );
document.write( '                    <p>臺中市政府運動局版權所有 Copyright © 2018. All Rights Reserved.</p>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"date\">\n' );
document.write( '                    <p>最後更新：2020/09/09</p>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </footer>\n' );
document.write( '\n' );
document.write( '    <a href=\"#top\">\n' );
document.write( '        <div class=\"back-top\">▲</div>\n' );
document.write( '    </a>' );
