document.write( '<div class=\"minibar\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <a href=\"#U\" id=\"AU\" title=\"右上方功能區塊\" accesskey=\"U\" tabindex=\"2\"></a>\n' );
document.write( '            <div class=\"navbar-L\">\n' );
document.write( '                <a href=\"index.html\">\n' );
document.write( '                    <img src=\"img/logo.png\" alt=\"logo\">\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"navbar-R\">\n' );
document.write( '                <div class=\"btn\">\n' );
document.write( '                    <ul>\n' );
document.write( '                        <li><a href=\"login.html\">登入</a></li>\n' );
document.write( '                        <li>|</li>\n' );
document.write( '                        <li><a href=\"sign-up-personal.html\">註冊</a></li>\n' );
document.write( '                    </ul>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '    <nav class=\"navbar\">\n' );
document.write( '        <div class=\"pc\">\n' );
document.write( '            <div class=\"navbar-R\">\n' );
document.write( '                <a href=\"news.html\">\n' );
document.write( '                    <h4>最新消息</h4>\n' );
document.write( '                </a>\n' );
document.write( '                <a href=\"download.html\">\n' );
document.write( '                    <h4>檔案下載</h4>\n' );
document.write( '                </a>\n' );
document.write( '                <a href=\"FAQ.html\">\n' );
document.write( '                    <h4>FAQ</h4>\n' );
document.write( '                </a>\n' );
document.write( '                <a href=\"signUp-explain.html\">\n' );
document.write( '                    <h4>報名教學</h4>\n' );
document.write( '                </a>\n' );
document.write( '                <a href=\"link.html\">\n' );
document.write( '                    <h4>相關連結</h4>\n' );
document.write( '                </a>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"member.html\">\n' );
document.write( '                        <h4>會員專區</h4>\n' );
document.write( '                    </a>\n' );
document.write( '                    <ul class=\"nav-list\">\n' );
document.write( '                        <li>\n' );
document.write( '                            <a href=\"case-apply.html\">\n' );
document.write( '                                <h4>案件申請</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </li>\n' );
document.write( '                        <li>\n' );
document.write( '                            <a href=\"case-list.html\">\n' );
document.write( '                                <h4>案件查詢</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </li>\n' );
document.write( '                        <li>\n' );
document.write( '                            <a href=\"change-data-personal.html\">\n' );
document.write( '                                <h4>會員資料修改</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </li>\n' );
document.write( '                    </ul>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"mobile\">\n' );
document.write( '            <div class=\"menu\">\n' );
document.write( '                <div class=\"fas fa-bars\">\n' );
document.write( '                </div>\n' );
document.write( '                <ul class=\"nav navbar-nav\">\n' );
document.write( '                    <li><a href=\"news.html\">最新消息</a></li>\n' );
document.write( '                    <li><a href=\"download.html\">檔案下載</a></li>\n' );
document.write( '                    <li><a href=\"FAQ.html\">FAQ</a></li>\n' );
document.write( '                    <li><a href=\"signUp-explain.html\">報名教學</a></li>\n' );
document.write( '                    <li><a href=\"link.html\">相關連結</a></li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" role=\"button\"\n' );
document.write( '                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            會員專區\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"case-apply.html\">\n' );
document.write( '                                <h4>案件申請</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"case-list.html\">\n' );
document.write( '                                <h4>案件查詢</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"change-data-personal.html\">\n' );
document.write( '                                <h4>會員資料修改</h4>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li><a href=\"login.html\">登入</a></li>\n' );
document.write( '                    <li><a href=\"sign-up-personal.html\">註冊</a></li>\n' );
document.write( '                </ul>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"logo\">\n' );
document.write( '                <a href=\"index.html\">\n' );
document.write( '                    <img src=\"img/logo.png\" alt=\"logo\">\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>' );
